### ISSUE TITLE
Add link to notification email when build finishes

### ISSUE THREAD

**Issue by NikolayMetchev** [etiennestuder/teamcity-build-scan-plugin#7]
Would it be possible to amend the success email that Teamcity emits whenever a build finshes to include the build scan link?

**Comment by etiennestuder** [comment]
@NikolayMetchev It may be possible. I'm not sure. One would have to look into the TeamCity APIs to see if it is possible.

I will close this issue since I will not have time to investigate but if you can find out how one can customize the TC notification emails programmatically, please let me know and we can reopen the issue, and I will be happy to implement a solution.
